import type { LucideIcon } from 'lucide-react'
import {
  BarChart3,
  Bot,
  Bug,
  Clock3,
  Code2,
  CreditCard,
  Database,
  FileText,
  GitBranch,
  Globe2,
  Grid3X3,
  Image,
  KeyRound,
  Logs,
  Mail,
  Package,
  Play,
  Server,
  ShoppingBag,
  Sparkles,
  Users,
  Workflow,
  Wrench,
} from 'lucide-react'
import { ServiceIcon } from '../domain/directory-types'

const icons = {
  [ServiceIcon.Bitwarden]: KeyRound,
  [ServiceIcon.Dozzle]: Logs,
  [ServiceIcon.GitHub]: GitBranch,
  [ServiceIcon.Gmail]: Mail,
  [ServiceIcon.Grafana]: BarChart3,
  [ServiceIcon.Immich]: Image,
  [ServiceIcon.YouTrack]: Sparkles,
  [ServiceIcon.AccountGroup]: Users,
  [ServiceIcon.AccountKey]: KeyRound,
  [ServiceIcon.BackupRestore]: Database,
  [ServiceIcon.Brain]: Sparkles,
  [ServiceIcon.Bug]: Bug,
  [ServiceIcon.Cash]: CreditCard,
  [ServiceIcon.ChartArea]: BarChart3,
  [ServiceIcon.ChartBox]: BarChart3,
  [ServiceIcon.ChartTimeline]: BarChart3,
  [ServiceIcon.Code]: Code2,
  [ServiceIcon.CreditCard]: CreditCard,
  [ServiceIcon.Database]: Database,
  [ServiceIcon.Docker]: Package,
  [ServiceIcon.Email]: Mail,
  [ServiceIcon.Ethernet]: Wrench,
  [ServiceIcon.DocumentEdit]: FileText,
  [ServiceIcon.Key]: KeyRound,
  [ServiceIcon.License]: FileText,
  [ServiceIcon.MonitorDashboard]: BarChart3,
  [ServiceIcon.Package]: Package,
  [ServiceIcon.Robot]: Bot,
  [ServiceIcon.Server]: Server,
  [ServiceIcon.ServerNetwork]: Server,
  [ServiceIcon.ShieldAccount]: KeyRound,
  [ServiceIcon.Shopping]: ShoppingBag,
  [ServiceIcon.SourceBranch]: Workflow,
  [ServiceIcon.SourceRepository]: GitBranch,
  [ServiceIcon.Storefront]: ShoppingBag,
  [ServiceIcon.TimelineClock]: Workflow,
  [ServiceIcon.Dashboard]: Grid3X3,
  [ServiceIcon.Watermark]: Globe2,
  [ServiceIcon.Web]: Globe2,
  [ServiceIcon.WebClock]: Clock3,
  [ServiceIcon.Npm]: Globe2,
  [ServiceIcon.Sentry]: Bug,
  [ServiceIcon.SigNoz]: BarChart3,
  [ServiceIcon.Telegram]: Play,
  [ServiceIcon.YouTube]: Play,
} satisfies Record<ServiceIcon, LucideIcon>

export function resolveServiceIcon(icon: ServiceIcon): LucideIcon {
  return icons[icon]
}
